### ISSUE TITLE
Missing time/date?

### ISSUE THREAD

**Issue by trevorturk** [IBM-Bluemix/weather-company-data-demo#6]
I noticed the example app running on http://weather-company-data-demo.eu-gb.mybluemix.net is missing the time/date and showing `undefined NaN, NaN` -- thanks for the demo, this is very helpful.

**Comment by phaedr** [comment]
@trevorturk I just had a look and everything seems to be back to normal.  There may have been sporadic issues with the weather data api.  If the issue is still happening for you, can you let me know what browser type and version you are using.  There were browser location support issues in the past.

**Comment by trevorturk** [comment]
Ah, yes. It's working for me in Chrome, but not in Safari Version 11.0 (13604.1.38.1.6)
